export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTIONS = 'DELETE_QUESTIONS';
export const INCREASE_TOTAL_SCORE = 'INCREASE_TOTAL_SCORE';
export const SUBMITTED_FALSE = 'SUBMITTED_FALS';
export const SUBMITTED_TRUE = ' SUBMITTED_TRUE';
