export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTIONS = 'DELETE_QUESTIONS';
export const CHANGE_TOTAL_SCORE = 'CHANGE_TOTAL_SCORE';
export const SUBMITTED_FALSE = 'SUBMITTED_FALSE';
export const SUBMITTED_TRUE = ' SUBMITTED_TRUE';
export const DELETE_TEST = 'DELETE_TEST';
export const ADD_TEST = 'ADD_TEST';
export const INCREASE_USER_SCORE = 'INCREASE_USER_SCORE';